
name: Test & Code Coverage

on:
  pull_request:
  push:
    paths:
      - 'src/**'
      - 'pom.xml'
    branches: 
      - develop

jobs:
   run_tests:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: maven
      - name: Test with Maven
        run: mvn cobertura:cobertura
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2.0.2
