# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY_1 }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Deploy
        run: |
          mvn clean package deploy -Prelease-sign-artifacts 
        env:
          OSSRH_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
