# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:

        
jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1.4.0
        with:
          gpg_private_key: ${{ secrets.GPG_SIGNING_KEY_TEST }}
          gpg_passphrase: ${{ secrets.GPG_SIGNING_KEY_PASSPHRASE_TEST }}
          nexus_username: ${{ secrets.NEXUS_USERNAME_TEST }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD_TEST }}
