# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - id: install-secret-key
        name: Install GPG secret key
        run: |
          cat <(echo -e "${{ secrets.GPG_SIGNING_KEY_TEST }}") | gpg --batch --import --default-key
          gpg --list-secret-keys --keyid-format LONG
      - name: List GPG keys
        run: |
          gpg --list-secret-keys 
      - name: Deploy
        run: |
          mvn -P release-sign-artifacts \
            --no-transfer-progress \
            --batch-mode -Dgpg.passphrase=${{ secrets.GPG_SIGNING_KEY_PASSPHRASE_TEST }} \
            --file pom.xml -s release/m2-settings.xml verify deploy
        env:
          OSSRH_USERNAME: ${{ secrets.NEXUS_USERNAME_TEST }}
          OSSRH_PASSWORD: ${{ secrets.NEXUS_PASSWORD_TEST }}
